name: Daily Tech Stack Update
on:
  schedule:
    - cron: '0 2 * * *' # 2:00 AM UTC every day
  workflow_dispatch: # Allow manual triggering


permissions:
    contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PNPM_VERSION: 10
  NODE_VERSION: 20.x

jobs:
    update-tld-data:
        if: github.event.repository.fork == false
        name: Update top level domain data
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: ${{ env.PNPM_VERSION }}

            - name: Setup node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'pnpm'
                  cache-dependency-path: 'pnpm-lock.yaml'

            - name: Install Dependencies
              run: pnpm install --prod --frozen-lockfile

            - name: Generate updated data
              run: pnpm start

            - name: Commit and Push Changes
              run: ./scripts/commit-changes.sh
              env:
                GITHUB_ACTOR: ${{ github.actor }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}